### ISSUE TITLE
EC2 instance not needed for SSM setup?

### ISSUE THREAD

**Issue by athewsey** [aws-samples/sagemaker-ssh-helper#12]
The [SSM setup guide](https://github.com/aws-samples/sagemaker-ssh-helper/blob/000fe0a02826ad78e17c96272e46e77c40aeb8cd/IAM_SSM_Setup.md) (section 2) currently guides users to set up SSM Advanced Tier by first creating a minimal EC2 instance...

But from my tests, I don't *think* this is mandatory, at least in all cases?

I was able to enable Advanced Tier simply by opening [Systems Manager > Fleet Manager in the Console](https://console.aws.amazon.com/systems-manager/managed-instances) and opening Account Management > Instance Tier settings. The below screenshot was taken after I'd already created an SSH Helper training job, but I could access the same screen beforehand too by clicking the orange "Get started" button if you navigate to Fleet Manager before any instances are set up.

![image](https://user-images.githubusercontent.com/19252478/214760145-c9619e48-9a76-4b1b-8d33-c721426d2b93.png)

I've been able to connect to the training job instance no problem, so pretty sure that at least in some cases users can just skip straight to step 2h? It would be nice to streamline the setup instructions if possible and maybe just give the EC2 option for troubleshooting problems?

The specific account I tested all the way through on is a management account in its AWS Organization (but the org only contains that one account).

**Comment by gilinachum** [comment]
Yes. The EC2 involvement is purely for verification purposes. We thought that it's better to bother a bit more during the setup process, than to continue on without verification, perhaps failing later on, when there are more moving making troubleshooting more complex.
@ivan-khvostishkov I think to make it more clear that the EC2 part is optional, okay?  2a. currently say `(you need it for successful setup and for verification).`

**Comment by ivan-khvostishkov** [comment]
Very good observation! I'll make another round of tests to simplify the procedure and update the docs accordingly.

**Comment by ivan-khvostishkov** [comment]
[IAM/SSM setup instructions](https://github.com/aws-samples/sagemaker-ssh-helper/blob/main/IAM_SSM_Setup.md) now have a minimal set or required steps and do not require EC2 instance.
