### ISSUE TITLE
Solution does not seem to support named profile when running  sm-local-ssh-ide <<kernel_gateway_app_name>>

### ISSUE THREAD

**Issue by weiwarren** [aws-samples/sagemaker-ssh-helper#14]
When initiate local ssh session using sm-local-ssh-ide, it does not support passing named profile to the command line.

`
 sm-local-ssh-ide <<kernel_gateway_app_name>> --profile dev
`

**Comment by ivan-khvostishkov** [comment]
Hi, Wei. It's already possible to pass the profile with the environment variable:
```
AWS_PROFILE=dev sm-local-ssh-ide sm-local-ssh-ide <<kernel_gateway_app_name>> 
```

See [AWS CLI environment variables](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) for more details.

**Comment by ivan-khvostishkov** [comment]
This is now added [to the FAQ](https://github.com/aws-samples/sagemaker-ssh-helper/blob/main/FAQ.md#how-to-configure-an-aws-cli-profile-to-work-with-sagemaker-ssh-helper).
