### ISSUE TITLE
[Feature Request] AWS SageMaker China region ssh helper support

### ISSUE THREAD

**Issue by KraftZzz** [aws-samples/sagemaker-ssh-helper#16]
When I use sagemaker-ssh-helper in China region, I get the following error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_9247/960454657.py in <cell line: 1>()
----> 1 ssh_wrapper = SSHModelWrapper.create(ssh_model, connection_wait_time_seconds=0)
      2 
      3 ssh_predictor = ssh_model.deploy(
      4     initial_instance_count=1,
      5     instance_type='ml.g4dn.xlarge',

~/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/sagemaker_ssh_helper/wrapper.py in create(cls, model, connection_wait_time_seconds)
    194     @classmethod
    195     def create(cls, model: sagemaker.model.Model, connection_wait_time_seconds: int = 600):
--> 196         result = SSHModelWrapper(model, connection_wait_time_seconds=connection_wait_time_seconds)
    197         result._augment()
    198         return result

~/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/sagemaker_ssh_helper/wrapper.py in __init__(self, model, ssm_iam_role, bootstrap_on_start, connection_wait_time_seconds)
    174                          bootstrap_on_start, connection_wait_time_seconds, model.sagemaker_session)
    175         if self.ssm_iam_role == '':
--> 176             self.ssm_iam_role = SSHEnvironmentWrapper.ssm_role_from_iam_arn(model.role)
    177         self.model = model
    178 

~/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/sagemaker_ssh_helper/wrapper.py in ssm_role_from_iam_arn(cls, iam_arn)
     77     def ssm_role_from_iam_arn(cls, iam_arn: str):
     78         if not iam_arn.startswith('arn:aws:iam::'):
---> 79             raise ValueError("iam_arn should start with 'arn:aws:iam::'")
     80         role_position = iam_arn.find(":role/")
     81         if role_position == -1:

ValueError: iam_arn should start with 'arn:aws:iam::'

Since resource ARNs in China often start with “arn:aws-cn:”, adjust your code to support China Regions

**Comment by ivan-khvostishkov** [comment]
Hi, KraftZzz! Great to see the interest in SageMaker SSH Helper in China Regions and thank you for testing it!
The ask is clear, I'll work on the fix.

**Comment by ivan-khvostishkov** [comment]
The support has been added and tested in the release v1.10.0.
