### ISSUE TITLE
[Feature] Copying file to an instance from local

### ISSUE THREAD

**Issue by ssmall41** [aws-samples/sagemaker-ssh-helper#18]
Sometimes I'd like to copy a file from my local host to a running SageMaker instance after the instance is already started. Is it possible to do this with SSM, or through some other solution?

Currently, I use an S3 bucket as a proxy (local host -> s3 bucket -> SageMaker instance). This works, but requires a few steps. I would prefer to directly transfer the file.

**Comment by ivan-khvostishkov** [comment]
Hi, @ssmall41, thank you for asking. Indeed, this is something that was already requested by some other users, and I already recorded the TODO item for it: 

https://github.com/aws-samples/sagemaker-ssh-helper/blob/f69943e4809f295d575a0890c2e5b7b16808985f/TODO#L6 .

Let’s keep this issue open for tracking your request until it’s implemented in a next release.

**Comment by ssmall41** [comment]
Thanks @ivan-khvostishkov. The TODO mentions SageMaker Studio. Would it also be possible to do this with Training Jobs or Endpoints?

**Comment by ivan-khvostishkov** [comment]
Yes, of course, thank you for checking. It is exactly the request for training jobs and endpoints. SageMaker Studio in this context is an example of IDE that doesn't have a native capability to copy files to remote machine. PyCharm, for example, can [synchronize files automatically with SFTP](https://www.jetbrains.com/help/pycharm/configuring-synchronization-with-a-remote-host.html), and this additional API brings little value to it. What IDE do you use on your local host?

**Comment by ivan-khvostishkov** [comment]
Yes, for PyCharm easier to use the native IDE deployment capability. For AWS CLI, I don’t know an easy way to do it. But if you use CLI helper scripts like `sm-local-ssh-training`, you will be able to use `rsync` CLI command to copy files to remote, as a workaround.

**Comment by ssmall41** [comment]
Thanks @ivan-khvostishkov Can you provide an example of how one would use `rsync` with the helper `sm-local-ssh-training`?

**Comment by ivan-khvostishkov** [comment]
Sure. The procedure should look like this (run from your local terminal in two separate tabs):

1. `sm-local-ssh-training connect <training-job-name>`
2. `rsync -avh -e 'ssh -i ~/.ssh/sagemaker-ssh-gw -p 10022' --delete project_dir/source_dir/ root@localhost:/opt/ml/code/`

**Comment by djmarti** [comment]
Thanks Ivan for the suggestion and the code. One minor issue with the `rsync` command above is that the files transferred to the remote instance end up owned by `root`, not `ec2-user`. This permission change prevents any further modification from the notebook end (although nothing stops us from making changes locally and synchronize them with `rsync). Fortunately, this can be easily fixed by passing `--chown 1000:1000`  to `rsync`:
```
rsync -rvh -e 'ssh -i ~/.ssh/sagemaker-ssh-gw -p 11022' --delete --chown 1000:1000 project_dir/source_dir/ root@localhost:/opt/ml/code

 (1000  seems to be the UID of `ec2-user`, but I am not sure how robust this is).

**Comment by ivan-khvostishkov** [comment]
Hi, @djmarti , thank you for the note. As I understand, you're trying to edit the files on the SageMaker notebook instance (i.e. using [SageMaker_SSH_Notebook.ipynb](https://github.com/aws-samples/sagemaker-ssh-helper/blob/main/SageMaker_SSH_Notebook.ipynb)). In this case, the owner of the file should be the 1000, and your command will work pretty well, indeed. I will think how to make it work in PyCharm, too.

**Comment by djmarti** [comment]
Hi Ivan. Apologies for the delay in responding. You are right, I was able to copy files from my local machine to the notebook instance, but I was unable to modify the newly copied files in the notebook instance. The reason was the owner of the newly copied files was no longer `ec2-user`.

**Comment by ivan-khvostishkov** [comment]
Starting from the new release v2.2.0, it's possible to copy files by using rsync and scp:

```
scp test.txt my-notebook-instance.notebook.sagemaker:
```

See [README](https://github.com/aws-samples/sagemaker-ssh-helper?#sshconfig) about `~/.ssh/config` file for more details.

**Comment by ivan-khvostishkov** [comment]
@djmarti Please feel free to reopen issue or create a new one if you still have questions
