### ISSUE TITLE
PyCharm debugging question

### ISSUE THREAD

**Issue by desinurch** [aws-samples/sagemaker-ssh-helper#3]
Hi, thanks for your wonderful work in this project. I am trying to do this part [Remote debugging with PyCharm Debug Server over SSH](https://github.com/aws-samples/sagemaker-ssh-helper#pycharm-debug-server) and I have a question:

When trying to debug a training session, the command `sm-local-ssh-training` failed even after using root. To clarify, I am running this inside the ssh connection.

```
$ ./sm-local-ssh-training connect pytorch-mnist-2022-11-15-09-46-35-587
sh: 11: ./sm-local-ssh-training: Permission denied
$ sudo ./sm-local-ssh-training connect pytorch-mnist-2022-11-15-09-46-35-587
./sm-local-ssh-training: line 17: python: command not found
```

If i run the command on local terminal (using Mac) this error happens
```
$ sm-local-ssh-training connect pytorch-mnist-2022-11-15-13-19-58-576
/opt/homebrew/bin/sm-local-ssh-training: line 17: python: command not found
INSTANCE_ID not provided
```
Am I missing something for debug setup?

**Comment by gilinachum** [comment]
Hi! To clarify: this command should run from your local terminal (Mac).
It appears you have no Python installed or it's missing from you path.
Install then verify Python3 is available on your Mac by running: `python --version`

**Comment by desinurch** [comment]
@gilinachum Thanks for your clarification! turns out my conda environment was not correctly activated. When debugging this shows up on Debug Server Console
```
Get test data loader
Processes 60000/60000 (100%) of train data
Processes 10000/10000 (100%) of test data
[2022-11-17 12:51:29.794 algo-1:41 INFO utils.py:27] RULE_JOB_STOP_SIGNAL_FILENAME: None
[2022-11-17 12:51:30.049 algo-1:41 INFO profiler_config_parser.py:102] User has disabled profiler.
[2022-11-17 12:51:30.050 algo-1:41 INFO json_config.py:91] Creating hook from json_config at /opt/ml/input/config/debughookconfig.json.
[2022-11-17 12:51:30.052 algo-1:41 INFO hook.py:199] tensorboard_dir has not been set for the hook. SMDebug will not be exporting tensorboard summaries.
Unhandled exception in thread started by <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x7f1f3732b048>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/_pydev_bundle/pydev_monkey.py", line 785, in __call__
    global_debugger.notify_thread_created(thread_id, t)
  File "/opt/conda/lib/python3.6/site-packages/pydevd.py", line 765, in notify_thread_created
    self.writer.add_command(self.cmd_factory.make_thread_created_message(thread))
  File "/opt/conda/lib/python3.6/site-packages/_pydevd_bundle/pydevd_comm.py", line 587, in make_thread_created_message
    cmdText = "<xml>" + self._thread_to_xml(thread) + "</xml>"
  File "/opt/conda/lib/python3.6/site-packages/_pydevd_bundle/pydevd_comm.py", line 573, in _thread_to_xml
    name = pydevd_xml.make_valid_xml_value(thread.getName())
  File "/opt/conda/lib/python3.6/site-packages/_pydevd_bundle/pydevd_xml.py", line 30, in make_valid_xml_value
    return s.replace("&", "&amp;").replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')
AttributeError: 'function' object has no attribute 'replace'
```
Any idea why this happened? this error did not show up when following the [Connecting to SageMaker training jobs with SSM](https://github.com/aws-samples/sagemaker-ssh-helper#training) step

**Comment by ivan-khvostishkov** [comment]
Hi, @desinurch.

As for the last comment about a function has no attribute ‘replace’, this is most likely the PyCharm issue - https://youtrack.jetbrains.com/issue/PY-40552 . 

You can try a one-liner patch for it, just as in this test — https://github.com/aws-samples/sagemaker-ssh-helper/blob/57b1f6369ce9e523a7951d23753a9f7f5a6a2022/tests/source_dir/training_debug/train_debug.py#L12 . 

Hope it helps! If not, please share the version of your pydevd-pycharm .

And thank you for the interest in the SageMaker SSH Helper!

Ivan

**Comment by desinurch** [comment]
@ivan-khvostishkov Perfect it works now! just a tip for anyone else trying this maybe you want to add project mappings on your Debug Server so the breakpoints will work as expected
