### ISSUE TITLE
Issue] STS client is not using regional endpoints

### ISSUE THREAD

**Issue by Tejaswi-Chillakuru** [aws-samples/sagemaker-ssh-helper#32]
Our use case is to start the SageMaker training job from the SageMaker Studio notebook and the studio is attached to a private vpc. 
When I try to create SSHEstimatorWrapper using below from my studio notebook
`ssh_wrapper = SSHEstimatorWrapper.create(pytorch_estimator, connection_wait_time_seconds=0)`
I'm getting `ConnectTimeoutError: Connect timeout on endpoint URL: "https://sts.amazonaws.com/"` exception. 
This is because since we have regional vpc endpoint and we can access only regional endpoints like https://sts.us-east-1.amazonaws.com/ . From [here](https://github.com/aws-samples/sagemaker-ssh-helper/blob/main/sagemaker_ssh_helper/wrapper.py#L72)  I see that this calls only global endpoint

We would need to pass region parameter during the initalization of sts boto3 client so that it uses sts regional endpoints based on teh region

**Comment by Tejaswi-Chillakuru** [comment]
We can set env variables to use the regional endpoint.
os.environ["AWS_STS_REGIONAL_ENDPOINTS"] = "regional"

**Comment by ivan-khvostishkov** [comment]
Released in v2.1.0:
https://github.com/aws-samples/sagemaker-ssh-helper/releases/tag/v2.1.0
