### ISSUE TITLE
sm-local-configure only works with bash like installations - no Powershell/CMD support / Windows support at all

### ISSUE THREAD

**Issue by mdaehnert** [aws-samples/sagemaker-ssh-helper#38]
Hi there.
When trying to install your solution, I can't execute the configuration via ```sm-local-configure```. As the script is written in bash, my Powershell will always try to open the file via Notepad instead of executing it.

Suggestions:
* Please provide the script in other shell languages as well
* Alternatively describe - in depth - what can be done instead of using this command

As of now, Windows users are excluded from using the plugin this way.

---

Update: Even if I install mingw64 and execute the command, it fails:
1. Python3 isn't found (on windows installation, Python is now just called ```python```)
2. The execution fails at ```sudo``` as this is no command for mingw64 installation

Please update documentation and highlight, that Windows is unsupported by the solution as of now.

**Comment by ivan-khvostishkov** [comment]
Hi, @mdaehnert , thank you for the proposal. In future these scripts will be probably rewritten in pure Python so they will work in any shell and OS that is supported by Python setuptools. 

So far, as a workaround, have you checked the "Is Windows supported?" question in the [FAQ.md](FAQ.md)? Git Bash is the suggested alternative that worked pretty well the last time when I tested it. Does it help in your case?

**Comment by FrancescoFarinola** [comment]
@ivan-khvostishkov any update on a pure Python script implementation for local connection from Windows? Do we have a roadmap/release date for this?

**Comment by ivan-khvostishkov** [comment]
Hi, @FrancescoFarinola , apologies for it taking a while for the fix. While pure Python implementation is not yet in the plan, I'm preparing the new release with the updated instructions where these scripts are simplified and made compatible with Git Bash in Windows.

**Comment by ivan-khvostishkov** [comment]
Released in the v2.2.0:

https://github.com/aws-samples/sagemaker-ssh-helper/releases/tag/v2.2.0

@mdaehnert Please, check if you can use it now (from GitBash), as described in the FAQ.
