### ISSUE TITLE
How to install VSCode, other apps in WebVNC view?

### ISSUE THREAD

**Issue by airlangga-gunawan-faculty** [aws-samples/sagemaker-ssh-helper#41]
Hi,

I've been following the instructions for getting WebVNC going and I've been successful in logging into the WebVNC environment. In the README.md file, you show that VSCode and PyCharm are running in this "browser-in-a-browser" environment.

My question is: how do you install these things in the WebVNC environment?

Furthermore, if I have a Dagster webserver serving a Dagit UI running on the KernelGateway app, if I were to configure the port forwarding properly, is it possible to see this UI in the WebVNC environment as well?

Thanks!

**Comment by ivan-khvostishkov** [comment]
Hi, @airlangga-gunawan-faculty , thank you for this question! First of all, what you see on the  screenshot is [XFCE desktop environment](https://www.xfce.org/), where only Dask web app is running in a "browser-in-a-browser" mode inside a single tab opened in Epiphany web browser:
![](https://github.com/aws-samples/sagemaker-ssh-helper/raw/main/images/webVNC.png)

Three other applications that are running in background are Terminal, PyCharm and Visual Studio Code. I understand that these apps may be confused with browser tabs. But these applications are not web applications, they are just normal Linux GUI desktop applications and you install them either through system package management tools (e.g. Terminal app comes already pre-installed) or download them and install just as you would do it on your local machine, e.g. downloading and running installation binaries from their official web sites:

1/ https://www.jetbrains.com/pycharm/download/
2/ https://code.visualstudio.com/download 

As for the second part, when you have a Dagster webserver serving a Dagit UI running on the KernelGateway app, and you want to access it from a browser running inside WebVNC, it's not necessary to configure additional port forwarding. The only port that has to be forwarded from KernelGateway to JupyterServer is VNC port `5901`, and it's done in the step 3 when you do `sm-local-ssh-ide connect <<kernel_gateway_app_name>>`. After you open a "browser-in-a-browser", you should be able to open your Dagit UI by navigating to the address that you've configured, e.g. `http://localhost:3000/`.  

Let me know if these answers are helpful.

**Comment by airlangga-gunawan-faculty** [comment]
Yep! Thank you Ivan :) I have other questions about this library that I will post in another issue.
