### ISSUE TITLE
 Enable advanced-instances tier to use Session Manager with your on-premises instances

### ISSUE THREAD

**Issue by marti-jorda-roca** [aws-samples/sagemaker-ssh-helper#44]
Hi when I configure my local connection to Sagemaker Studio with:

` sm-local-ssh-ide connect <my kernel gateway>`

The process fails in the last step with the following error:

```
An error occurred (BadRequest) when calling the StartSession operation: Enable advanced-instances tier to use Session Manager with your on-premises instances
Connection closed by UNKNOWN port 65535
```

What is happening here?

**Comment by ivan-khvostishkov** [comment]
Hi, @marti-jorda-roca , have you checked the [Setting up your AWS account with IAM and SSM configuration](https://github.com/aws-samples/sagemaker-ssh-helper/blob/main/IAM_SSM_Setup.md) doc?

If you follow the manual setup, you have to enable the advanced instances tier:

> Manual setup
> 1. Setup Systems Manager (SSM)

**Comment by ivan-khvostishkov** [comment]
@marti-jorda-roca I'm closing this issue for now. Please reopen or create a new one if you need further guidance.

Btw, the new version v2.2.0 has been just published and I recommend to look into the new `sm-ssh` tool.
