### ISSUE TITLE
Connecting to SageMaker BYOC Inference Endpoint?

### ISSUE THREAD

**Issue by npow** [aws-samples/sagemaker-ssh-helper#45]
Hi is there a way to connect to a Sagemaker inference endpoint running my custom Docker container? If it matters, I'm using https://github.com/aws/sagemaker-inference-toolkit

**Comment by ivan-khvostishkov** [comment]
Hi, @npow , thanks for the interest in SSH Helper.
There should be no difference whether it's your custom container or the pre-built container. As soon as you can update the inference code inside your container [according to the README](https://github.com/aws-samples/sagemaker-ssh-helper?tab=readme-ov-file#inference), it will work.

Let me know if you have more questions.
