### ISSUE TITLE
SSH port forwarding to KernelGateway app container

### ISSUE THREAD

**Issue by isimova** [aws-samples/sagemaker-ssh-helper#47]
Hello,

Is it possible to use one of the sagemaker-ssh-helper scripts to enable port forwarding between SageMaker Studio's JupyterServer and a running KernelGateway app container? I am developing a Streamlit application which runs on localhost on a given port, e.g. 8053. If I start the application from the System Terminal I can access the application UI in the browser under domain.studio.region.sagemaker.aws/jupyter/default/proxy/8053. However the app is  computationally intensive, so I would like to run it from a container Image Terminal instead, in order to take advantage of the container's resources, while still being able to access the application UI in the browser as before. I tried to forward the port on which the application is running inside the container to the Jupyter Server port using `sm-local-ssh-ide`, but go the following error: `SSMManager:No instance IDs found`
![image](https://github.com/aws-samples/sagemaker-ssh-helper/assets/1225915/b701d3ff-a110-40c7-8d19-2166f4536f91)

Perhaps this is not the intended use of the script? Your help would be greatly appreciated as I am new to SageMaker.

**Comment by ivan-khvostishkov** [comment]
Hi, @isimova , thanks for your interest in SageMaker SSH Helper! This is the supported use case.

However, it seems you forgot pass the kernel gateway name to the command:

```shell
sm-local-ssh-ide connect <<kernel_gateway_app_name>> -L ...
```

Also check the note in [IAM_SSM_Setup.md](https://github.com/aws-samples/sagemaker-ssh-helper/blob/main/IAM_SSM_Setup.md):

> Note: If you want to run and debug the SageMaker jobs from SageMaker Studio, and not from your local IDE, attach both SSHSageMakerServerPolicy and SSHSageMakerClientPolicy to the SageMaker execution role.

This note also applies to SageMaker kernel gateway containers. I will update the comment.

Also very important to understand that note web apps will work through Jupyter Proxy and I recommend to use WebVNC instead, see  [Web VNC section](https://github.com/aws-samples/sagemaker-ssh-helper?tab=readme-ov-file#web-vnc) in the documentation.

There's a note there about the Dask web app, but the same can apply to Streamlit, too:

> note, that Dask web app may not work properly through Jupyter Proxy, so VNC is the recommended alternative

Let me know if you have more questions.

**Comment by ivan-khvostishkov** [comment]
I'm closing the issue for now. Please feel free to reopen or create a new one if you need further guidance.
