### ISSUE TITLE
[Question] How to connect to sagemaker notebooks

### ISSUE THREAD

**Issue by kirill-fedyanin** [aws-samples/sagemaker-ssh-helper#52]
You've mentioned on reddit it's possible to connect to notebook instance in sagemaker with the library. (https://www.reddit.com/r/aws/comments/gibbtg/guide_sagemaker_ssh_to_notebook_instances/)
I couldn't see how to do it in the readme; I've tried to just do `sagemaker_ssh_helper.setup_and_start_ssh()`in script, but it asks for one of the wrappers and I don't see one that would match.
```
WARNING: SageMaker SSH Helper is not correctly initialized. Did you forget to call wrapper.create() _before_ fit() / run() / transform() / deploy()?
```

Could you please point the direction on how to approach this?

**Comment by ivan-khvostishkov** [comment]
Hi, @kirill-fedyanin , thank you for your interest in SageMaker SSH Helper! 

Take a look at the [FAQ: Are SageMaker notebook instances supported?](https://github.com/aws-samples/sagemaker-ssh-helper/blob/main/FAQ.md#are-sagemaker-notebook-instances-supported)

Hope this helps

**Comment by kirill-fedyanin** [comment]
Ivan, thanks for the answer
I feel like this runs container inside notebook instance and connects to it
You think it's possible to connect to instance itself, akin to notebook terminal, but over ssh?

**Comment by ivan-khvostishkov** [comment]
Hi, @kirill-fedyanin , theoretically it should be possible but practically it's very difficult because Notebook Instance has already another SSM agent running and this is one of the reasons why SSH Helper does not support it. 

Any reason why you want to connect to the instance itself and why the container doesn't work for you?

**Comment by kirill-fedyanin** [comment]
Because notebooks, environments and data not in this container. 
I think it's more straighforward to just use ec2 for now. Appreciate your time and answers anyway, thank you.
