### ISSUE TITLE
does ssh helper support sagemaker's remote debug's ssm connection?

### ISSUE THREAD

**Issue by qingyuan18** [aws-samples/sagemaker-ssh-helper#54]
ssh helper can't get ssm instance id for sagemaker remote debug job

using sagamaker remote debug , we can use ssm client to connect to training job container via :
**aws ssm start-session --target sagemaker-training-job:${job_name}_algo-1**

but when use ssh helper to do the ssh turnel , it can't find ssm instance id : 
**@6c7e67c16c37 ~ % sm-local-ssh-training connect ${job_name}
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO:sagemaker-ssh-helper:Resolving training instance IDs through SSM tags
INFO:sagemaker-ssh-helper:Remote training logs are at https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/$252Faws$252Fsagemaker$252FTrainingJobs$3FlogStreamNameFilter$3Dsd-finetuning-test-2024-03-15-08-32-30-966$252F
INFO:sagemaker-ssh-helper:Estimator metadata is at https://us-west-2.console.aws.amazon.com/sagemaker/home?region=us-west-2#/jobs/sd-finetuning-test-2024-03-15-08-32-30-966
INFO:sagemaker-ssh-helper:SSMManager:Querying SSM instance IDs for training job sd-finetuning-test-2024-03-15-08-32-30-966, expected instance count = 0
INFO:sagemaker-ssh-helper:SSMManager:Using AWS Region: us-west-2
INFO:sagemaker-ssh-helper:SSMManager:No instance IDs found. Retrying. Is SSM Agent running on the remote? Check the remote logs. Seconds left before time out: 300**

**Comment by ivan-khvostishkov** [comment]
Hi, @qingyuan18 , as the log message suggests, did you try to check if SSM Agent running on the remote by checking the the remote logs?

You should see there more details.

**Comment by ivan-khvostishkov** [comment]
@qingyuan18 I'm closing this issue for now. Please feel free to reopen or create a new one if you need further guidance.
