### ISSUE TITLE
does ssh helper support byoc sagemaker endpoint? 

### ISSUE THREAD

**Issue by qingyuan18** [aws-samples/sagemaker-ssh-helper#60]
hello team
        we have a byoc sagemaker endpoint which want to debug, but I found the ssh helper only has byos mode sagemaker endpoint to setup:

model = estimator.create_model(
    entry_point='inference_ssh.py',
    source_dir='source_dir/inference/',
    dependencies=[SSHModelWrapper.dependency_dir()]  # <--NEW 
    # (alternatively, add sagemaker_ssh_helper into requirements.txt 
    # inside source dir) --
)

is there anyway we can debug BYOC sm endpoint?  do you have any guide for that?

Thanks

**Comment by ivan-khvostishkov** [comment]
Hi, @qingyuan18 , in the FAQ there are couple of related questions mentioning Dockerfile:

1/ [What if I want to train and deploy a model as a simple Estimator in my own container, without passing entry_point and source_dir?](https://github.com/aws-samples/sagemaker-ssh-helper/blob/main/FAQ.md#what-if-i-want-to-train-and-deploy-a-model-as-a-simple-estimator-in-my-own-container-without-passing-entry_point-and-source_dir)

2/ [I'm running SageMaker in a VPC. Do I need to make extra configuration?](https://github.com/aws-samples/sagemaker-ssh-helper/blob/main/FAQ.md#im-running-sagemaker-in-a-vpc-do-i-need-to-make-extra-configuration)

Do these answers help?

Please also make sure you've checked the [BYOC blog post](https://medium.com/@pandey.vikesh/why-bring-your-own-container-to-amazon-sagemaker-and-how-to-do-it-right-bc158fe41ed1) by Vikesh Pandey and validated that your case doesn't fall into one of the mentioned in the section "When you don’t really need BYOC" .

**Comment by ivan-khvostishkov** [comment]
@qingyuan18 I'm closing this issue for now. Please feel free to reopen or create a new one if you need further guidance.
